<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ColorNotes</AssemblyName>
    <RootNamespace>ColorNotes</RootNamespace>
    <ApplicationIcon>Assets\ColorNotes.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\ColorNotes.png" />
  </ItemGroup>
</Project>
